/* singleton */
if(!window.__suduI18N){window.__suduI18N=1;
(function(){
/* SuDu Studio — lightweight i18n: EN source, FR/ES/DE dictionaries.
   Walker swaps matching text nodes + alt/placeholder/title/aria-label/data-info attrs.
   Unmatched strings (proper nouns, project names) stay as-is. */
(function(){
var T=[
["Skip to work", "Aller aux projets", "Ir a los proyectos", "Zu den Projekten", "作品へスキップ"],
["Work", "Projets", "Proyectos", "Projekte", "作品"],
["Studio", "Studio", "Estudio", "Studio", "スタジオ"],
["Contact", "Contact", "Contacto", "Kontakt", "お問い合わせ"],
["Architecture", "Architecture", "Arquitectura", "Architektur", "建築"],
["Interiors", "Intérieurs", "Interiores", "Innenräume", "インテリア"],
["Design", "Design", "Diseño", "Design", "デザイン"],
["Residential Schematic Concept", "Concept schématique résidentiel", "Concepto esquemático residencial", "Schematisches Wohnkonzept", "住宅の基本構想"],
["In Progress", "En cours", "En curso", "In Arbeit", "進行中"],
["In progress", "En cours", "En curso", "In Arbeit", "進行中"],
["Scroll", "Défiler", "Desplazar", "Scrollen", "スクロール"],
["Architecture and interiors, developed together.", "Architecture et intérieurs, conçus ensemble.", "Arquitectura e interiores, desarrollados en conjunto.", "Architektur und Innenräume, gemeinsam entwickelt.", "建築とインテリアを、ともに設計する。"],
["From concept through delivery, SuDu works across buildings, interiors and branded environments.", "Du concept à la livraison, SuDu intervient sur les bâtiments, les intérieurs et les environnements de marque.", "Del concepto a la entrega, SuDu trabaja en edificios, interiores y entornos de marca.", "Vom Konzept bis zur Übergabe arbeitet SuDu an Gebäuden, Innenräumen und Markenwelten.", "構想から引き渡しまで、SuDuは建築、インテリア、ブランド空間にわたって取り組みます。"],
["Offerings", "Services", "Servicios", "Leistungen", "業務内容"],
["All work", "Tous les projets", "Todos los proyectos", "Alle Projekte", "すべての作品"],
["New builds, renovations, and additions: concept through construction documentation.", "Constructions neuves, rénovations et agrandissements : du concept aux documents de construction.", "Obra nueva, renovaciones y ampliaciones: del concepto a la documentación de obra.", "Neubauten, Sanierungen und Erweiterungen: vom Konzept bis zur Ausführungsplanung.", "新築、改修、増築。構想から実施設計図書まで。"],
["Spatial planning, material direction, and millwork for residential and commercial interiors.", "Aménagement spatial, direction des matériaux et ébénisterie pour intérieurs résidentiels et commerciaux.", "Planificación espacial, dirección de materiales y carpintería para interiores residenciales y comerciales.", "Raumplanung, Materialkonzept und Einbaumöbel für Wohn- und Gewerbeinterieurs.", "住宅および商業インテリアの空間計画、マテリアルディレクション、造作家具。"],
["Commercial", "Commercial", "Comercial", "Gewerbe", "商業"],
["Hospitality, retail, and workplace environments where identity and space work as one system.", "Environnements hôteliers, commerciaux et de travail où identité et espace forment un seul système.", "Entornos de hospitalidad, comercio y trabajo donde identidad y espacio funcionan como un solo sistema.", "Gastronomie-, Einzelhandels- und Arbeitsumgebungen, in denen Identität und Raum als ein System wirken.", "アイデンティティと空間がひとつの仕組みとして働く、ホスピタリティ、リテール、ワークプレイスの環境。"],
["Advisory", "Conseil", "Asesoría", "Beratung", "アドバイザリー"],
["Concept studies, feasibility, and design direction for allied practices and developers.", "Études conceptuelles, faisabilité et direction de design pour cabinets partenaires et promoteurs.", "Estudios de concepto, viabilidad y dirección de diseño para estudios aliados y promotores.", "Konzeptstudien, Machbarkeit und Designleitung für Partnerbüros und Projektentwickler.", "協働する設計事務所やデベロッパーのためのコンセプトスタディ、事業可能性検討、デザインディレクション。"],
["Selected Work", "Projets choisis", "Obra seleccionada", "Ausgewählte Arbeiten", "主な作品"],
["Private Residential", "Résidentiel privé", "Residencial privado", "Privates Wohnen", "個人住宅"],
["A private residence and gallery organized around the display of a personal art collection.", "Une résidence privée et galerie organisée autour d'une collection d'art personnelle.", "Una residencia privada y galería organizada en torno a una colección de arte personal.", "Ein privates Wohnhaus mit Galerie, gestaltet um eine persönliche Kunstsammlung.", "個人のアートコレクションの展示を軸に構成された、住宅とギャラリー。"],
["Location", "Lieu", "Ubicación", "Ort", "所在地"],
["Scope", "Mandat", "Alcance", "Umfang", "業務範囲"],
["Architecture, Interiors", "Architecture, intérieurs", "Arquitectura, interiores", "Architektur, Innenräume", "建築、インテリア"],
["Hospitality", "Hôtellerie", "Hospitalidad", "Gastronomie", "ホスピタリティ"],
["A standalone brick heritage building; coral tile and brass metalwork demonstrating how closely brand identity and physical space can be built together.", "Un bâtiment patrimonial en brique ; carrelage corail et laiton démontrant à quel point identité de marque et espace physique peuvent se construire ensemble.", "Un edificio patrimonial de ladrillo; azulejo coral y latón que demuestran cuán estrechamente pueden construirse juntos la identidad de marca y el espacio físico.", "Ein denkmalgeschützter Backsteinbau; korallenrote Fliesen und Messing zeigen, wie eng Markenidentität und physischer Raum zusammen entstehen können.", "独立した煉瓦造の歴史的建築。コーラル色のタイルと真鍮の金物が、ブランドのアイデンティティと物理的な空間をどれほど近く築けるかを示しています。"],
["Interiors, Material Direction", "Intérieurs, direction des matériaux", "Interiores, dirección de materiales", "Innenräume, Materialkonzept", "インテリア、マテリアルディレクション"],
["Community · Wellness", "Communauté · Bien-être", "Comunidad · Bienestar", "Gemeinschaft · Wellness", "コミュニティ・ウェルネス"],
["Youth Recovery Centre", "Centre de rétablissement pour jeunes", "Centro de recuperación juvenil", "Jugend-Genesungszentrum", "ユース・リカバリーセンター"],
["A youth recovery and wellness environment built around calm, residential-scale space.", "Un environnement de rétablissement pour jeunes conçu autour d'espaces calmes à l'échelle résidentielle.", "Un entorno de recuperación juvenil construido en torno a espacios tranquilos de escala residencial.", "Ein Genesungs- und Wellnessumfeld für Jugendliche, gebaut um ruhige Räume im Wohnmaßstab.", "住宅スケールの穏やかな空間を軸に構成した、若者のための回復とウェルネスの環境。"],
["Architecture, with MES Architecture", "Architecture, avec MES Architecture", "Arquitectura, con MES Architecture", "Architektur, mit MES Architecture", "建築、MES Architectureとの協働"],
["Status", "Statut", "Estado", "Status", "状況"],
["Renewal of the concourse, podium, and exterior plazas at a major downtown intersection, creating an active public throughway with food and retail.", "Renouvellement du hall, du podium et des places extérieures à une intersection majeure du centre-ville, créant un passage public animé avec restauration et commerces.", "Renovación del vestíbulo, el podio y las plazas exteriores en una intersección céntrica clave, creando un paso público activo con gastronomía y comercio.", "Erneuerung von Concourse, Podium und Außenplätzen an einer zentralen Innenstadtkreuzung — ein belebter öffentlicher Durchgang mit Gastronomie und Handel.", "ダウンタウンの主要交差点における、コンコース、ポディウム、外部広場の刷新。飲食と物販を備えた、人の流れのある公共の通り抜けを生み出します。"],
["Collaboration", "Collaboration", "Colaboración", "Zusammenarbeit", "協働"],
["with DIALOG", "avec DIALOG", "con DIALOG", "mit DIALOG", "DIALOGとの協働"],
["Experience Index", "Index d'expérience", "Índice de experiencia", "Erfahrungsindex", "実績インデックス"],
["Open", "Ouvrir", "Abrir", "Öffnen", "開く"],
["Close", "Fermer", "Cerrar", "Schließen", "閉じる"],
["Beyond the selected work", "Au-delà des projets choisis", "Más allá de la obra seleccionada", "Über die ausgewählten Arbeiten hinaus", "主な作品のその先へ"],
["Residential & Private", "Résidentiel et privé", "Residencial y privado", "Wohnen & Privat", "住宅・個人邸"],
["Custom homes, major renovations, additions, interiors, and private galleries.", "Maisons sur mesure, rénovations majeures, agrandissements, intérieurs et galeries privées.", "Casas a medida, renovaciones mayores, ampliaciones, interiores y galerías privadas.", "Maßgefertigte Häuser, umfassende Sanierungen, Erweiterungen, Innenräume und private Galerien.", "注文住宅、大規模改修、増築、インテリア、プライベートギャラリー。"],
["Hospitality, Retail & Experience", "Hôtellerie, commerce et expérience", "Hospitalidad, comercio y experiencia", "Gastronomie, Handel & Erlebnis", "ホスピタリティ、リテール、体験"],
["Restaurants, bars, cafés, retail interiors, and customer-facing environments.", "Restaurants, bars, cafés, intérieurs commerciaux et environnements clients.", "Restaurantes, bares, cafés, interiores comerciales y entornos de atención al cliente.", "Restaurants, Bars, Cafés, Ladeninterieurs und kundenorientierte Umgebungen.", "レストラン、バー、カフェ、店舗インテリア、顧客と接する環境。"],
["Commercial & Community", "Commercial et communautaire", "Comercial y comunitario", "Gewerbe & Gemeinschaft", "商業とコミュニティ"],
["Repositioning, public realm, workplace, community housing, and feasibility studies.", "Repositionnement, espace public, milieux de travail, logement communautaire et études de faisabilité.", "Reposicionamiento, espacio público, lugares de trabajo, vivienda comunitaria y estudios de viabilidad.", "Repositionierung, öffentlicher Raum, Arbeitswelten, Gemeinschaftswohnen und Machbarkeitsstudien.", "リポジショニング、パブリックスペース、ワークプレイス、コミュニティ住宅、事業可能性調査。"],
["Enoch, Tsuut’ina & Smoky Lake Recovery Centres", "Centres de rétablissement d'Enoch, Tsuut'ina et Smoky Lake", "Centros de recuperación de Enoch, Tsuut'ina y Smoky Lake", "Genesungszentren Enoch, Tsuut'ina & Smoky Lake", "Enoch、Tsuut’ina、Smoky Lakeのリカバリーセンター"],
["The Studio", "Le Studio", "El Estudio", "Das Studio", "スタジオについて"],
["Each project is a response, not a repetition.", "Chaque projet est une réponse, pas une répétition.", "Cada proyecto es una respuesta, no una repetición.", "Jedes Projekt ist eine Antwort, keine Wiederholung.", "どの計画も、繰り返しではなく応答です。"],
["SuDu begins with the conditions of the project: place, use, material, budget and people. The work is developed from the overall idea through to the smallest detail.", "SuDu part des conditions du projet : le lieu, l'usage, la matière, le budget et les personnes. Le travail se développe de l'idée d'ensemble jusqu'au plus petit détail.", "SuDu parte de las condiciones del proyecto: el lugar, el uso, el material, el presupuesto y las personas. El trabajo se desarrolla desde la idea general hasta el detalle más pequeño.", "SuDu geht von den Bedingungen des Projekts aus: Ort, Nutzung, Material, Budget und Menschen. Die Arbeit entwickelt sich von der Gesamtidee bis zum kleinsten Detail.", "SuDuは、その計画の条件から始めます。場所、用途、素材、予算、そして人。全体の構想から細部に至るまで、一貫して展開します。"],
["Based", "Implantation", "Base", "Standort", "拠点"],
["Practice", "Pratique", "Práctica", "Praxis", "事業領域"],
["Architecture, Interiors, Advisory", "Architecture, intérieurs, conseil", "Arquitectura, interiores, asesoría", "Architektur, Innenräume, Beratung", "建築、インテリア、アドバイザリー"],
["Sectors", "Secteurs", "Sectores", "Sektoren", "分野"],
["Residential, Hospitality, Commercial, Community", "Résidentiel, hôtellerie, commercial, communautaire", "Residencial, hospitalidad, comercial, comunitario", "Wohnen, Gastronomie, Gewerbe, Gemeinschaft", "住宅、ホスピタリティ、商業、コミュニティ"],
["Start a project", "Démarrer un projet", "Iniciar un proyecto", "Ein Projekt starten", "プロジェクトを始める"],
["Get in touch", "Nous joindre", "Contáctenos", "Kontakt aufnehmen", "ご連絡ください"],
["© 2026 SuDu Studio Architecture", "© 2026 SuDu Studio Architecture", "© 2026 SuDu Studio Architecture", "© 2026 SuDu Studio Architecture", "© 2026 SuDu Studio Architecture"],
["Dark mode", "Mode sombre", "Modo oscuro", "Dunkelmodus", "ダークモード"],
["Toggle dark mode", "Basculer le mode sombre", "Alternar modo oscuro", "Dunkelmodus umschalten", "ダークモードの切り替え"],
["West Coast Marine Drive concept, single-line drawing", "Concept Marine Drive côte ouest, dessin au trait", "Concepto Marine Drive costa oeste, dibujo de línea", "West Coast Marine Drive Konzept, Strichzeichnung", "West Coast Marine Driveのコンセプト、一筆書きのドローイング"],
["West Vancouver private residence and gallery", "Résidence privée et galerie à West Vancouver", "Residencia privada y galería en West Vancouver", "Privatresidenz und Galerie in West Vancouver", "West Vancouverの個人住宅とギャラリー"],
["Wilfreds hospitality interior with coral tile and brass", "Intérieur Wilfreds avec carrelage corail et laiton", "Interior de Wilfreds con azulejo coral y latón", "Wilfreds-Interieur mit Korallenfliesen und Messing", "コーラルタイルと真鍮によるWilfredsのホスピタリティインテリア"],
["Youth Recovery Centre exterior", "Extérieur du Centre de rétablissement pour jeunes", "Exterior del Centro de recuperación juvenil", "Außenansicht des Jugend-Genesungszentrums", "ユース・リカバリーセンターの外観"],
["ATB Place Reimagined concourse", "Hall d'ATB Place Reimagined", "Vestíbulo de ATB Place Reimagined", "Concourse von ATB Place Reimagined", "ATB Place Reimaginedのコンコース"],
["6,000 sq ft private residence | Architecture & Interiors", "Résidence privée de 6 000 pi² | Architecture et intérieurs", "Residencia privada de 560 m² | Arquitectura e interiores", "6.000 sq ft Privatresidenz | Architektur & Innenräume", "約560㎡の個人住宅｜建築・インテリア"],
["Multi-unit apartment block | Architecture", "Immeuble résidentiel multilogement | Architecture", "Bloque de apartamentos multifamiliar | Arquitectura", "Mehrfamilienhaus | Architektur", "集合住宅｜建築"],
["Twenty-unit apartment block | Architecture", "Immeuble de vingt logements | Architecture", "Bloque de veinte apartamentos | Arquitectura", "Wohnblock mit zwanzig Einheiten | Architektur", "20戸の集合住宅｜建築"],
["Mexican restaurant for chef Scott Linquist of Coyo Taco | Lincoln Road, Miami Beach", "Restaurant mexicain pour le chef Scott Linquist de Coyo Taco | Lincoln Road, Miami Beach", "Restaurante mexicano para el chef Scott Linquist de Coyo Taco | Lincoln Road, Miami Beach", "Mexikanisches Restaurant für Chefkoch Scott Linquist von Coyo Taco | Lincoln Road, Miami Beach", "Coyo Tacoのシェフ Scott Linquist によるメキシコ料理店｜Lincoln Road、Miami Beach"],
["Revitalization of the landmark restaurant Chez Pipo | Nice, France", "Revitalisation du restaurant emblématique Chez Pipo | Nice, France", "Revitalización del emblemático restaurante Chez Pipo | Niza, Francia", "Revitalisierung des traditionsreichen Restaurants Chez Pipo | Nizza, Frankreich", "名店 Chez Pipo の再生｜フランス、ニース"],
["STEM academy environment | West Vancouver, BC", "Environnement d'académie STIM | West Vancouver, C.-B.", "Entorno de academia STEM | West Vancouver, BC", "STEM-Akademie-Umgebung | West Vancouver, BC", "STEMアカデミーの環境｜ブリティッシュコロンビア州West Vancouver"],
["Office environment | Workplace Interiors", "Environnement de bureau | Intérieurs de travail", "Entorno de oficina | Interiores de trabajo", "Büroumgebung | Arbeitsplatz-Interieurs", "オフィス環境｜ワークプレイスインテリア"],
["Recovery centres for the Enoch, Tsuut’ina and Smoky Lake (Métis) communities | Community wellness", "Centres de rétablissement pour les communautés d'Enoch, Tsuut'ina et Smoky Lake (Métis) | Bien-être communautaire", "Centros de recuperación para las comunidades de Enoch, Tsuut'ina y Smoky Lake (Métis) | Bienestar comunitario", "Genesungszentren für die Gemeinschaften Enoch, Tsuut'ina und Smoky Lake (Métis) | Gemeinschaftswohl", "Enoch、Tsuut’ina、Smoky Lake（メティ）各コミュニティのリカバリーセンター｜コミュニティ・ウェルネス"],
["Selected projects were led by members of our team while at previous practices, and are shown here as part of their portfolio of work.", "Certains projets ont été dirigés par des membres de notre équipe au sein de cabinets précédents et figurent ici comme partie de leur portfolio.", "Algunos proyectos fueron dirigidos por miembros de nuestro equipo en estudios anteriores y se muestran aquí como parte de su portafolio.", "Ausgewählte Projekte wurden von Teammitgliedern in früheren Büros geleitet und werden hier als Teil ihres Portfolios gezeigt.", "一部のプロジェクトは、当スタジオのメンバーが以前所属していた事務所で担当したものであり、個人の実績として掲載しています。"],
["Say hello", "Écrivez-nous", "Salúdenos", "Sagen Sie hallo", "ご挨拶を"],
["Hospitality · Retail", "Hôtellerie · Commerce", "Hospitalidad · Comercio", "Gastronomie · Handel", "ホスピタリティ・リテール"],
["Hospitality · Entertainment", "Hôtellerie · Divertissement", "Hospitalidad · Entretenimiento", "Gastronomie · Unterhaltung", "ホスピタリティ・エンターテインメント"],
["Retail · Banking", "Commerce · Bancaire", "Comercio · Banca", "Handel · Banking", "リテール・銀行"],
["Hospitality · Concept", "Hôtellerie · Concept", "Hospitalidad · Concepto", "Gastronomie · Konzept", "ホスピタリティ・コンセプト"],
["Hospitality · Private Club", "Hôtellerie · Club privé", "Hospitalidad · Club privado", "Gastronomie · Privatclub", "ホスピタリティ・プライベートクラブ"],
["Retail · Healthcare", "Commerce · Santé", "Comercio · Salud", "Handel · Gesundheit", "リテール・ヘルスケア"],
["Commercial · Community", "Commercial · Communautaire", "Comercial · Comunitario", "Gewerbe · Gemeinschaft", "商業・コミュニティ"],
["Community Housing", "Logement communautaire", "Vivienda comunitaria", "Gemeinschaftswohnen", "コミュニティ住宅"],
["The work changes with the context.", "Le travail change avec le contexte.", "El trabajo cambia con el contexto.", "Die Arbeit ändert sich mit dem Kontext.", "仕事は文脈とともに変わります。"],
["The approach does not.", "La démarche, non.", "El enfoque, no.", "Die Herangehensweise nicht.", "取り組み方は変わりません。"],
["SuDu works across architecture, interiors and design direction. Each project begins with its particular conditions: place, use, material, budget and people. We develop the work from the overall idea through to the smallest detail, looking for what is necessary, what belongs, and what can be removed.", "SuDu intervient en architecture, en intérieurs et en direction de design. Chaque projet commence par ses conditions propres : le lieu, l'usage, la matière, le budget et les personnes. Nous développons le travail de l'idée d'ensemble jusqu'au plus petit détail, en cherchant ce qui est nécessaire, ce qui a sa place, et ce qui peut être retiré.", "SuDu trabaja en arquitectura, interiores y dirección de diseño. Cada proyecto comienza por sus condiciones particulares: el lugar, el uso, el material, el presupuesto y las personas. Desarrollamos el trabajo desde la idea general hasta el detalle más pequeño, buscando lo necesario, lo que corresponde y lo que puede quitarse.", "SuDu arbeitet in Architektur, Innenräumen und Designleitung. Jedes Projekt beginnt bei seinen eigenen Bedingungen: Ort, Nutzung, Material, Budget und Menschen. Wir entwickeln die Arbeit von der Gesamtidee bis zum kleinsten Detail und suchen dabei, was notwendig ist, was dazugehört und was entfallen kann.", "SuDuは、建築、インテリア、デザインディレクションにわたって取り組みます。どの計画も、その固有の条件から始まります。場所、用途、素材、予算、そして人。全体の構想から細部に至るまで仕事を進め、必要なもの、ふさわしいもの、そして省けるものを見極めます。"],
["Founders", "Fondateurs", "Fundadores", "Gründer", "共同創業者"],
["Partner + Principal Architect", "Associé + Architecte principal", "Socio + Arquitecto principal", "Partner + Leitender Architekt", "パートナー／主任建築家"],
["With over 40 years of architectural experience, Mike is a pillar of the profession, known for his measured leadership and depth of expertise across project types. His portfolio spans institutional, educational, civic, residential, and commercial work throughout Western Canada.", "Fort de plus de 40 ans d'expérience en architecture, Mike est un pilier de la profession, reconnu pour son leadership mesuré et sa profondeur d'expertise. Son portfolio couvre des projets institutionnels, éducatifs, civiques, résidentiels et commerciaux dans l'Ouest canadien.", "Con más de 40 años de experiencia en arquitectura, Mike es un pilar de la profesión, conocido por su liderazgo mesurado y su profunda experiencia. Su portafolio abarca obras institucionales, educativas, cívicas, residenciales y comerciales en el oeste de Canadá.", "Mit über 40 Jahren Architekturerfahrung ist Mike eine Säule des Berufsstands, bekannt für seine besonnene Führung und Expertise über alle Projekttypen hinweg. Sein Portfolio umfasst institutionelle, Bildungs-, öffentliche, Wohn- und Gewerbebauten in Westkanada.", "40年を超える建築の経験をもつMikeは、落ち着いたリーダーシップと幅広い用途への深い知見で知られる、この職能の柱となる存在です。その実績は、カナダ西部全域の公共施設、教育施設、市民施設、住宅、商業建築に及びます。"],
["Over the course of his career, Mike has led complex multi-stakeholder projects, shepherded heritage-sensitive renovations, and designed award-winning public spaces. He is equally comfortable navigating municipal processes as he is resolving construction details.", "Au fil de sa carrière, Mike a dirigé des projets complexes à multiples intervenants, mené des rénovations patrimoniales sensibles et conçu des espaces publics primés. Il est aussi à l'aise dans les processus municipaux que dans les détails de construction.", "A lo largo de su carrera, Mike ha dirigido proyectos complejos con múltiples actores, renovaciones sensibles al patrimonio y espacios públicos premiados. Se mueve con la misma soltura en los procesos municipales que en los detalles constructivos.", "Im Laufe seiner Karriere hat Mike komplexe Projekte mit vielen Beteiligten geleitet, denkmalsensible Sanierungen begleitet und preisgekrönte öffentliche Räume entworfen. Er bewegt sich ebenso sicher in kommunalen Verfahren wie in Baudetails.", "キャリアを通じてMikeは、多くの関係者が関わる複雑なプロジェクトを率い、歴史的建造物に配慮した改修を導き、受賞歴のある公共空間を設計してきました。行政手続きの調整も、施工ディテールの解決も、同じように得意としています。"],
["Designer + Project Director", "Designer + Directrice de projet", "Diseñadora + Directora de proyectos", "Designerin + Projektdirektorin", "デザイナー／プロジェクトディレクター"],
["Jennifer is in her 18th year of consulting across the built environment, with a focus on interiors, project strategy, stakeholder alignment and integrated design. She works with multi-disciplinary teams across North and Central America, bringing together clients, developers, builders, and registered consultants around a shared vision.", "Jennifer en est à sa 18e année de conseil dans l'environnement bâti, avec un accent sur les intérieurs, la stratégie de projet, l'alignement des parties prenantes et le design intégré. Elle travaille avec des équipes multidisciplinaires en Amérique du Nord et centrale, réunissant clients, promoteurs, constructeurs et consultants agréés autour d'une vision commune.", "Jennifer lleva 18 años de consultoría en el entorno construido, con enfoque en interiores, estrategia de proyecto, alineación de actores y diseño integrado. Trabaja con equipos multidisciplinarios en América del Norte y Central, reuniendo a clientes, promotores, constructores y consultores registrados en torno a una visión compartida.", "Jennifer ist im 18. Jahr als Beraterin in der gebauten Umwelt tätig, mit Fokus auf Innenräume, Projektstrategie, Stakeholder-Abstimmung und integriertes Design. Sie arbeitet mit multidisziplinären Teams in Nord- und Mittelamerika und vereint Kunden, Entwickler, Bauunternehmen und registrierte Fachplaner hinter einer gemeinsamen Vision.", "Jenniferは、建築環境に関わるコンサルティング18年目を迎えています。インテリア、プロジェクト戦略、関係者間の合意形成、そして統合的なデザインに注力してきました。北米・中米の多分野にわたるチームと協働し、クライアント、デベロッパー、施工者、有資格コンサルタントを共通のビジョンのもとにまとめます。"],
["Her work has included wellness and community facilities, affordable housing, and culturally significant projects with Indigenous Nations in Alberta.", "Son travail comprend des installations de bien-être et communautaires, du logement abordable et des projets culturellement significatifs avec des Nations autochtones en Alberta.", "Su trabajo incluye instalaciones de bienestar y comunitarias, vivienda asequible y proyectos culturalmente significativos con Naciones Indígenas en Alberta.", "Ihre Arbeit umfasst Wellness- und Gemeinschaftseinrichtungen, bezahlbaren Wohnraum und kulturell bedeutsame Projekte mit indigenen Nationen in Alberta.", "これまでの仕事には、ウェルネス施設やコミュニティ施設、アフォーダブル住宅、そしてアルバータ州の先住民ネイションとの文化的に重要なプロジェクトが含まれます。"],
["Designer + Design Director", "Designer + Directeur de design", "Diseñador + Director de diseño", "Designer + Designdirektor", "デザイナー／デザインディレクター"],
["Joe is a designer with 25 years of experience across the built environment, interiors, retail, hospitality, and residential design. Known for clarity of vision and cross-sector versatility, his work ranges from custom residences and multifamily housing to high-profile hospitality and retail interiors.", "Joe est un designer avec 25 ans d'expérience dans l'environnement bâti, les intérieurs, le commerce, l'hôtellerie et le résidentiel. Reconnu pour sa clarté de vision et sa polyvalence, son travail va des résidences sur mesure et du logement multifamilial aux intérieurs hôteliers et commerciaux de haut niveau.", "Joe es un diseñador con 25 años de experiencia en el entorno construido, interiores, comercio, hospitalidad y diseño residencial. Conocido por su claridad de visión y versatilidad, su trabajo abarca desde residencias a medida y vivienda multifamiliar hasta interiores de hospitalidad y comercio de alto perfil.", "Joe ist Designer mit 25 Jahren Erfahrung in der gebauten Umwelt, Innenräumen, Einzelhandel, Gastronomie und Wohndesign. Bekannt für klare Vision und sektorübergreifende Vielseitigkeit, reicht seine Arbeit von maßgefertigten Residenzen und Mehrfamilienhäusern bis zu hochkarätigen Gastronomie- und Ladeninterieurs.", "Joeは、建築環境、インテリア、リテール、ホスピタリティ、住宅デザインにわたる25年の経験をもつデザイナーです。ビジョンの明快さと分野を越えた対応力で知られ、その仕事は注文住宅や集合住宅から、注目度の高いホスピタリティ・リテールのインテリアまで及びます。"],
["Notably, Joe led the strategic planning, concept development, and design direction for ATB Financial’s “Branches of the Future”, a multi-year initiative to reimagine the bank’s flagship and neighbourhood locations across Alberta. His portfolio includes restaurants for award-winning chefs, branded commercial spaces, and design systems that balance atmosphere with operational function. He provides senior design leadership from early concepts through refined execution, working with the studio’s registered professionals where regulated services are required.", "Joe a notamment dirigé la planification stratégique, le développement conceptuel et la direction de design des « Branches of the Future » d'ATB Financial, une initiative pluriannuelle pour réinventer les succursales phares et de quartier de la banque en Alberta. Son portfolio comprend des restaurants pour chefs primés, des espaces commerciaux de marque et des systèmes de design équilibrant atmosphère et fonction. Il assure un leadership de design senior du concept à l'exécution, avec les professionnels agréés du studio lorsque des services réglementés sont requis.", "Cabe destacar que Joe dirigió la planificación estratégica, el desarrollo conceptual y la dirección de diseño de “Branches of the Future” de ATB Financial, una iniciativa plurianual para reinventar las sucursales insignia y de barrio del banco en Alberta. Su portafolio incluye restaurantes para chefs premiados, espacios comerciales de marca y sistemas de diseño que equilibran atmósfera y función. Aporta liderazgo senior de diseño del concepto a la ejecución, con los profesionales registrados del estudio cuando se requieren servicios regulados.", "Joe leitete insbesondere die strategische Planung, Konzeptentwicklung und Designleitung von ATB Financials „Branches of the Future“, einer mehrjährigen Initiative zur Neugestaltung der Flagship- und Quartiersfilialen der Bank in Alberta. Sein Portfolio umfasst Restaurants für preisgekrönte Küchenchefs, Marken-Gewerberäume und Designsysteme, die Atmosphäre und Betrieb ausbalancieren. Er bietet Senior-Designführung vom frühen Konzept bis zur Ausführung, mit den registrierten Fachleuten des Studios, wo regulierte Leistungen erforderlich sind.", "とりわけJoeは、ATB Financialの「Branches of the Future」において、戦略立案、コンセプト開発、デザインディレクションを主導しました。アルバータ州全域の旗艦店舗と地域店舗を再構想する、複数年にわたる取り組みです。その実績には、受賞歴のあるシェフのためのレストラン、ブランドを体現する商業空間、雰囲気と運営上の機能を両立させるデザインシステムが含まれます。初期のコンセプトから精緻な実施まで上級のデザインリーダーシップを担い、法規で有資格者の関与が求められる業務では、スタジオの登録専門家と協働します。"],
["Line portrait of the three SuDu Studio founders", "Portrait au trait des trois fondateurs de SuDu Studio", "Retrato de línea de los tres fundadores de SuDu Studio", "Strichporträt der drei Gründer von SuDu Studio", "SuDu Studioの3人の共同創業者を描いた線画の肖像"],
["Every project begins", "Chaque projet commence", "Cada proyecto comienza", "Jedes Projekt beginnt", "すべてのプロジェクトは"],
["with a conversation.", "par une conversation.", "con una conversación.", "mit einem Gespräch.", "対話から始まります。"],
["I'm interested in", "Je m'intéresse à", "Me interesa", "Ich interessiere mich für", "関心のある分野"],
["Name", "Nom", "Nombre", "Name", "お名前"],
["Email", "Courriel", "Correo", "E-Mail", "メールアドレス"],
["About the project", "À propos du projet", "Sobre el proyecto", "Zum Projekt", "プロジェクトについて"],
["Send inquiry", "Envoyer la demande", "Enviar consulta", "Anfrage senden", "送信する"],
["Sends straight to the studio, or write us directly at", "Envoyé directement au studio, ou écrivez-nous directement à", "Se envía directamente al estudio, o escríbanos directamente a", "Geht direkt an das Studio, oder schreiben Sie uns direkt an", "スタジオへ直接送信されます。メールでのご連絡は"],
["Sending…", "Envoi…", "Enviando…", "Wird gesendet…", "送信中…"],
["Inquiry sent", "Demande envoyée", "Consulta enviada", "Anfrage gesendet", "送信しました"],
["Inquiry sent. We’ll reply by email.", "Demande envoyée. Nous répondrons par courriel.", "Consulta enviada. Le responderemos por correo.", "Anfrage gesendet. Wir antworten per E-Mail.", "送信しました。メールでご返信します。"],
["That did not send. Please try again, or email us directly.", "L’envoi a échoué. Réessayez, ou écrivez-nous directement.", "No se pudo enviar. Inténtelo de nuevo, o escríbanos directamente.", "Das Senden hat nicht geklappt. Bitte erneut versuchen, oder schreiben Sie uns direkt.", "送信できませんでした。もう一度お試しいただくか、直接メールをお送りください。"],
["Please fill in your name, your email, and a note about the project.", "Veuillez indiquer votre nom, votre courriel et une note sur le projet.", "Indique su nombre, su correo y una nota sobre el proyecto.", "Bitte Name, E-Mail und eine Notiz zum Projekt ausfüllen.", "お名前、メールアドレス、プロジェクトについてのご記入をお願いします。"],
["That email address does not look complete.", "Cette adresse courriel semble incomplète.", "Esa dirección de correo parece incompleta.", "Diese E-Mail-Adresse scheint unvollständig.", "メールアドレスが不完全なようです。"],
["Project", "Projet", "Proyecto", "Projekt", "プロジェクト"],
["Select an interest to explore what it can include, then tap the branches that fit.", "Choisissez un intérêt pour explorer ce qu'il peut inclure, puis touchez les branches pertinentes.", "Seleccione un interés para explorar lo que puede incluir, luego toque las ramas que correspondan.", "Wählen Sie ein Interesse, um zu sehen, was es umfassen kann, und tippen Sie dann auf die passenden Zweige.", "関心のある分野を選ぶと内容が展開します。当てはまる項目をタップしてください。"],
["Common questions", "Questions fréquentes", "Preguntas frecuentes", "Häufige Fragen", "よくあるご質問"],
["Your name", "Votre nom", "Su nombre", "Ihr Name", "お名前"],
["you@email.com", "vous@courriel.com", "usted@correo.com", "sie@email.de", "you@email.com"],
["Site, scope, timeline, budget range, and what you are hoping to build.", "Site, portée, échéancier, budget et ce que vous espérez construire.", "Sitio, alcance, plazos, presupuesto y lo que espera construir.", "Grundstück, Umfang, Zeitplan, Budgetrahmen und was Sie bauen möchten.", "敷地、業務範囲、スケジュール、ご予算の目安、そして実現したいことをお書きください。"],
["Related Work", "Projets liés", "Obra relacionada", "Verwandte Arbeiten", "関連する作品"],
["From the archive", "Des archives", "Del archivo", "Aus dem Archiv", "アーカイブより"],
["Next project", "Projet suivant", "Siguiente proyecto", "Nächstes Projekt", "次のプロジェクト"],
["Drop a detail photo", "Déposez une photo de détail", "Suelte una foto de detalle", "Detailfoto ablegen", "ディテール写真をドロップ"],
["Drop an interior photo", "Déposez une photo d'intérieur", "Suelte una foto interior", "Innenfoto ablegen", "インテリア写真をドロップ"],
["Drop a wide photo", "Déposez une photo d'ensemble", "Suelte una foto general", "Weitwinkelfoto ablegen", "引きの写真をドロップ"],
["Sited at the rear of a south-facing property, the study explored three architectural directions for a private office, gallery, and rare car collection. The selected concept, H.21.01 / White Box, uses a minimal white volume, an open lower level, and a restrained material language to balance privacy, landscape, light, and display.", "Implantée à l'arrière d'une propriété orientée sud, l'étude a exploré trois directions architecturales pour un bureau privé, une galerie et une collection de voitures rares. Le concept retenu, H.21.01 / White Box, utilise un volume blanc minimal, un niveau inférieur ouvert et un langage matériel sobre pour équilibrer intimité, paysage, lumière et exposition.", "Situado en la parte trasera de una propiedad orientada al sur, el estudio exploró tres direcciones arquitectónicas para una oficina privada, galería y colección de autos raros. El concepto seleccionado, H.21.01 / White Box, usa un volumen blanco mínimo, un nivel inferior abierto y un lenguaje material contenido para equilibrar privacidad, paisaje, luz y exhibición.", "Am hinteren Ende eines nach Süden ausgerichteten Grundstücks untersuchte die Studie drei architektonische Richtungen für ein privates Büro, eine Galerie und eine Sammlung seltener Autos. Das gewählte Konzept, H.21.01 / White Box, nutzt ein minimales weißes Volumen, ein offenes Untergeschoss und eine zurückhaltende Materialsprache, um Privatsphäre, Landschaft, Licht und Präsentation auszubalancieren.", "南向きの敷地の奥に位置し、個人のオフィス、ギャラリー、希少車コレクションのための3つの建築的方向性を検討しました。採用案のH.21.01／White Boxは、ミニマルな白いヴォリューム、開放的な下階、抑制された素材の言語によって、プライバシー、ランドスケープ、光、展示のバランスをとっています。"],
["Selected concept", "Concept retenu", "Concepto seleccionado", "Gewähltes Konzept", "採用案"],
["Drawings", "Dessins", "Planos", "Zeichnungen", "図面"],
["H.21.01 / White Box floor plans", "Plans d'étage H.21.01 / White Box", "Plantas H.21.01 / White Box", "Grundrisse H.21.01 / White Box", "H.21.01／White Box 平面図"],
["Alternative study", "Étude alternative", "Estudio alternativo", "Alternativstudie", "別案のスタディ"],
["H.21.03 / The Cantilever floor plans", "Plans d'étage H.21.03 / The Cantilever", "Plantas H.21.03 / The Cantilever", "Grundrisse H.21.03 / The Cantilever", "H.21.03／The Cantilever 平面図"],
["A standalone brick heritage building, rebuilt from the inside out as a single hospitality idea.", "Un bâtiment patrimonial en brique, reconstruit de l'intérieur comme une seule idée hôtelière.", "Un edificio patrimonial de ladrillo, reconstruido de adentro hacia afuera como una sola idea de hospitalidad.", "Ein denkmalgeschützter Backsteinbau, von innen heraus als eine einzige gastronomische Idee neu aufgebaut.", "独立した煉瓦造の歴史的建築を、ひとつのホスピタリティの構想のもとに内側からつくり直しました。"],
["Custom millwork, soft colour, natural materials, and playful mural work give the room a warm, residential scale. Space and millwork by the studio, mural by Vanguard Works, brand development with Shaun Brandt: a demonstration of how closely identity and physical place can be built together.", "Ébénisterie sur mesure, couleurs douces, matériaux naturels et murale ludique donnent à la salle une échelle chaleureuse et résidentielle. Espace et ébénisterie par le studio, murale de Vanguard Works, développement de marque avec Shaun Brandt : une démonstration de la façon dont identité et lieu physique peuvent se construire ensemble.", "Carpintería a medida, colores suaves, materiales naturales y un mural lúdico dan a la sala una escala cálida y residencial. Espacio y carpintería del estudio, mural de Vanguard Works, desarrollo de marca con Shaun Brandt: una demostración de cuán estrechamente pueden construirse juntos la identidad y el lugar físico.", "Maßgefertigte Einbauten, sanfte Farben, natürliche Materialien und eine verspielte Wandmalerei geben dem Raum einen warmen, wohnlichen Maßstab. Raum und Einbauten vom Studio, Wandbild von Vanguard Works, Markenentwicklung mit Shaun Brandt: ein Beleg dafür, wie eng Identität und physischer Ort zusammen entstehen können.", "造作家具、やわらかな色彩、自然素材、そして遊び心のある壁画が、この部屋に住宅のような温かいスケールを与えています。空間と造作はスタジオ、壁画はVanguard Works、ブランド開発はShaun Brandtとの協働。アイデンティティと実際の場所がどれほど近くつくられうるかを示す実例です。"],
["A custom residence developed from massing studies through exterior material resolution.", "Une résidence sur mesure développée des études volumétriques à la résolution des matériaux extérieurs.", "Una residencia a medida desarrollada desde estudios volumétricos hasta la resolución de materiales exteriores.", "Eine maßgefertigte Residenz, entwickelt von Massenstudien bis zur äußeren Materialauflösung.", "ヴォリュームのスタディから外装素材の決定までを通して開発した注文住宅。"],
["The design began as a study of the site’s long views and grade, testing massing options before committing to a form. Exterior materials were resolved early so the concept and its construction logic developed together.", "Le design a commencé par une étude des vues et de la pente du site, testant des options volumétriques avant de fixer une forme. Les matériaux extérieurs ont été résolus tôt pour que le concept et sa logique constructive évoluent ensemble.", "El diseño comenzó como un estudio de las vistas y la pendiente del sitio, probando opciones volumétricas antes de definir una forma. Los materiales exteriores se resolvieron temprano para que el concepto y su lógica constructiva se desarrollaran juntos.", "Der Entwurf begann als Studie der weiten Blicke und des Geländes, mit Massenvarianten vor der Festlegung einer Form. Die Außenmaterialien wurden früh bestimmt, sodass Konzept und Baulogik gemeinsam reiften.", "設計は、敷地からの長い眺望と高低差の検討から始まり、形を決める前に複数のヴォリューム案を試しました。外装材を早い段階で確定させたことで、コンセプトと構法の論理が並行して育っていきました。"],
["A single family residence lifted into the palm canopy of a hillside site.", "Une résidence unifamiliale hissée dans la canopée de palmiers d'un site à flanc de colline.", "Una residencia unifamiliar elevada al dosel de palmeras de un sitio en ladera.", "Ein Einfamilienhaus, in das Palmendach eines Hanggrundstücks gehoben.", "斜面地のヤシの樹冠へと持ち上げられた一戸建て住宅。"],
["A compact volume raised on concrete pilotis, opening the main living level to the treetops and long views while the ground plane stays planted and shaded beneath. Deep overhangs, screened openings, and a pared palette of white render, warm timber, and glass are shaped around the tropical climate.", "Un volume compact surélevé sur pilotis de béton, ouvrant le niveau de vie principal sur la cime des arbres et les vues lointaines, tandis que le sol reste planté et ombragé. Débords profonds, ouvertures grillagées et palette épurée d'enduit blanc, de bois chaud et de verre, façonnés pour le climat tropical.", "Un volumen compacto elevado sobre pilotes de hormigón, abriendo el nivel principal a las copas de los árboles y las vistas lejanas mientras el suelo permanece plantado y sombreado. Aleros profundos, aberturas con celosías y una paleta sobria de revoque blanco, madera cálida y vidrio, moldeados para el clima tropical.", "Ein kompaktes Volumen auf Betonstützen, das die Hauptwohnebene zu den Baumkronen und weiten Blicken öffnet, während der Boden bepflanzt und beschattet bleibt. Tiefe Überstände, verschattete Öffnungen und eine reduzierte Palette aus weißem Putz, warmem Holz und Glas, geformt für das tropische Klima.", "コンクリートのピロティに載るコンパクトなヴォリュームが、主たる居住階を樹冠と遠景へ開き、地面はその下で緑に覆われたまま日陰に保たれます。深い庇、スクリーン状の開口、そして白い左官、温かみのある木、ガラスに絞った素材構成は、熱帯の気候に合わせてかたちづくられています。"],
["Casita 01 / Site plan and floor plans", "Casita 01 / Plan de site et plans d'étage", "Casita 01 / Plano de sitio y plantas", "Casita 01 / Lageplan und Grundrisse", "Casita 01／配置図・平面図"],
["A 4,000 sq ft modern residence on the edge of Mackenzie Ravine.", "Une résidence moderne de 4 000 pi² en bordure du ravin Mackenzie.", "Una residencia moderna de 370 m² al borde del barranco Mackenzie.", "Eine moderne 4.000 sq ft Residenz am Rand der Mackenzie-Schlucht.", "Mackenzie Ravineの縁に建つ約370㎡のモダンな住宅。"],
["Flat-roofed volumes of dark standing-seam cladding and warm cedar sit low among mature spruce, with full-height glazing opening the main living spaces to a concrete terrace and the ravine beyond. The design began as a set of napkin sketches and carried that directness through to the built work.", "Des volumes à toit plat de bardage sombre à joints debout et de cèdre chaud s'installent bas parmi les épinettes matures, avec des vitrages toute hauteur ouvrant les espaces de vie sur une terrasse de béton et le ravin. Le design est né de croquis sur serviette et a porté cette franchise jusqu'à l'œuvre bâtie.", "Volúmenes de techo plano con revestimiento oscuro de junta alzada y cedro cálido se asientan bajos entre abetos maduros, con acristalamiento de altura completa abriendo los espacios principales a una terraza de hormigón y el barranco. El diseño nació de bocetos en servilleta y llevó esa franqueza hasta la obra construida.", "Flachdachvolumen aus dunkler Stehfalzverkleidung und warmem Zedernholz liegen niedrig zwischen alten Fichten, mit raumhoher Verglasung zu einer Betonterrasse und der Schlucht dahinter. Der Entwurf begann als Serviettenskizzen und trug diese Direktheit bis ins gebaute Werk.", "濃色の立ハゼ葺き外装と温かみのあるシダーによる陸屋根のヴォリュームが、成熟したトウヒの間に低く据えられ、全面高のガラスが主要な居住空間をコンクリートのテラスと渓谷へ開きます。設計はナプキンに描いたスケッチから始まり、その率直さを竣工まで持ち続けました。"],
["Process", "Processus", "Proceso", "Prozess", "プロセス"],
["Napkin sketches", "Croquis sur serviette", "Bocetos en servilleta", "Serviettenskizzen", "ナプキンのスケッチ"],
["Floor plans", "Plans d'étage", "Plantas", "Grundrisse", "平面図"],
["Renewal of the concourse, podium, and exterior plazas at a major downtown intersection.", "Renouvellement du hall, du podium et des places extérieures à une intersection majeure du centre-ville.", "Renovación del vestíbulo, el podio y las plazas exteriores en una intersección céntrica clave.", "Erneuerung von Concourse, Podium und Außenplätzen an einer zentralen Innenstadtkreuzung.", "ダウンタウンの主要交差点における、コンコース、ポディウム、外部広場の刷新。"],
["For client HOOP, the study turns an internalized office podium into an active public throughway: food and retail addressing the street, plazas reworked as everyday civic space, and a stronger connection between the towers, tenants, and downtown residents. Design team: Joe Johnson (Makespace Group) with DIALOG.", "Pour le client HOOP, l'étude transforme un podium de bureaux fermé en passage public animé : restauration et commerces sur rue, places repensées comme espace civique quotidien et lien renforcé entre tours, locataires et résidents du centre-ville. Équipe de design : Joe Johnson (Makespace Group) avec DIALOG.", "Para el cliente HOOP, el estudio convierte un podio de oficinas cerrado en un paso público activo: gastronomía y comercio hacia la calle, plazas replanteadas como espacio cívico cotidiano y una conexión más fuerte entre torres, inquilinos y residentes del centro. Equipo de diseño: Joe Johnson (Makespace Group) con DIALOG.", "Für den Kunden HOOP verwandelt die Studie ein nach innen gekehrtes Büropodium in einen belebten öffentlichen Durchgang: Gastronomie und Handel zur Straße, Plätze als alltäglicher Stadtraum und eine stärkere Verbindung zwischen Türmen, Mietern und Innenstadtbewohnern. Designteam: Joe Johnson (Makespace Group) mit DIALOG.", "クライアントHOOPのために、内向きだったオフィスのポディウムを人の流れのある公共の通り抜けへと変えるスタディです。通りに面する飲食と物販、日常の市民空間として再構成された広場、そしてタワーとテナント、ダウンタウンに暮らす人々をより強く結ぶ関係。設計チーム：Joe Johnson（Makespace Group）、DIALOGとの協働。"],
["An intimate Italian restaurant on Jasper Avenue, built around a narrow room and a long bar.", "Un restaurant italien intime sur Jasper Avenue, construit autour d'une salle étroite et d'un long bar.", "Un íntimo restaurante italiano en Jasper Avenue, construido en torno a una sala estrecha y una barra larga.", "Ein intimes italienisches Restaurant an der Jasper Avenue, gebaut um einen schmalen Raum und eine lange Bar.", "Jasper Avenueの細長い部屋と長いバーカウンターを軸に構成した、親密なイタリア料理店。"],
["A tight plan resolved through custom millwork, warm material choices, and careful lighting: a restaurant for an award-winning chef where the room supports the food rather than competing with it.", "Un plan serré résolu par l'ébénisterie sur mesure, des matériaux chauds et un éclairage soigné : un restaurant pour un chef primé où la salle soutient la cuisine au lieu de rivaliser avec elle.", "Una planta ajustada resuelta con carpintería a medida, materiales cálidos e iluminación cuidada: un restaurante para un chef premiado donde la sala apoya la comida en lugar de competir con ella.", "Ein knapper Grundriss, gelöst durch maßgefertigte Einbauten, warme Materialien und sorgfältige Beleuchtung: ein Restaurant für einen preisgekrönten Chefkoch, in dem der Raum das Essen trägt, statt mit ihm zu konkurrieren.", "狭小な平面を、造作家具、温かみのある素材選び、丁寧な照明計画によって解いています。受賞歴のあるシェフのためのレストランとして、部屋が料理と競うのではなく、料理を支えるように設えました。"],
["A standing-room spuntini bar, compact and precise, next door to Corso 32.", "Un bar à spuntini debout, compact et précis, voisin de Corso 32.", "Un bar de spuntini de pie, compacto y preciso, junto a Corso 32.", "Eine Spuntini-Stehbar, kompakt und präzise, direkt neben Corso 32.", "Corso 32の隣にある、コンパクトで精緻な立ち飲みのスプンティーニバー。"],
["A small footprint treated as a virtue: a single counter-focused room where millwork, lighting, and material restraint do the spatial work. Designed as a companion piece to Corso 32.", "Une petite empreinte traitée comme une vertu : une salle centrée sur un comptoir où l'ébénisterie, l'éclairage et la retenue matérielle font le travail spatial. Conçu comme un pendant de Corso 32.", "Una huella pequeña tratada como virtud: una sala centrada en el mostrador donde la carpintería, la iluminación y la contención material hacen el trabajo espacial. Diseñado como pieza compañera de Corso 32.", "Eine kleine Fläche als Tugend: ein einziger, auf den Tresen ausgerichteter Raum, in dem Einbauten, Licht und materielle Zurückhaltung die räumliche Arbeit leisten. Als Gegenstück zu Corso 32 entworfen.", "小さな面積を美点として扱いました。カウンターに焦点を絞ったひと部屋で、造作、照明、素材の抑制が空間をつくります。Corso 32の姉妹店として設計。"],
["A bright, pared-back Italian room completing the Jasper Avenue trio.", "Une salle italienne lumineuse et épurée complétant le trio de Jasper Avenue.", "Una sala italiana luminosa y sobria que completa el trío de Jasper Avenue.", "Ein heller, reduzierter italienischer Raum, der das Trio an der Jasper Avenue vollendet.", "Jasper Avenueの3店をしめくくる、明るく削ぎ落とされたイタリアの部屋。"],
["Where Corso 32 is dark and Bar Bricco is compact, Uccellino is open and light: pale surfaces, simple lines, and a calm dining room that lets daylight and the table carry the experience.", "Là où Corso 32 est sombre et Bar Bricco compact, Uccellino est ouvert et clair : surfaces pâles, lignes simples et une salle calme qui laisse la lumière du jour et la table porter l'expérience.", "Donde Corso 32 es oscuro y Bar Bricco compacto, Uccellino es abierto y claro: superficies pálidas, líneas simples y un comedor sereno que deja que la luz del día y la mesa lleven la experiencia.", "Wo Corso 32 dunkel und Bar Bricco kompakt ist, ist Uccellino offen und hell: helle Oberflächen, einfache Linien und ein ruhiger Speiseraum, in dem Tageslicht und Tisch das Erlebnis tragen.", "Corso 32が暗く、Bar Briccoが小さいのに対し、Uccellinoは開放的で明るい店です。淡い面、簡潔な線、そして日の光とテーブルそのものが体験を担う静かなダイニング。"],
["Two rooms, one kitchen: a tasting-menu dining room and its adjoining bar for chef Ben Staley.", "Deux salles, une cuisine : une salle de menu dégustation et son bar attenant pour le chef Ben Staley.", "Dos salas, una cocina: un comedor de menú degustación y su bar contiguo para el chef Ben Staley.", "Zwei Räume, eine Küche: ein Degustationsraum und die angrenzende Bar für Chefkoch Ben Staley.", "ふたつの部屋にひとつの厨房。シェフBen Staleyのためのテイスティングメニューのダイニングと、隣接するバー。"],
["The Alder Room, an intimate multi-course tasting room, and Alta, its more casual bar and a la carte companion, share one kitchen and one pared-back material language: dark surfaces, warm wood, and precise lighting that puts the food and the craft at centre stage. Named one of Canada’s Best New Restaurants by Air Canada’s enRoute in 2017. Logo design by Denis Lenarduzzi.", "L'Alder Room, salle de dégustation intime, et Alta, son pendant plus décontracté au bar et à la carte, partagent une cuisine et un langage matériel épuré : surfaces sombres, bois chaud et éclairage précis qui placent la cuisine et le métier au centre. Nommé parmi les meilleurs nouveaux restaurants du Canada par enRoute d'Air Canada en 2017. Logo par Denis Lenarduzzi.", "El Alder Room, un íntimo salón de degustación, y Alta, su compañero más casual de bar y a la carta, comparten una cocina y un lenguaje material sobrio: superficies oscuras, madera cálida e iluminación precisa que ponen la comida y el oficio en el centro. Nombrado uno de los mejores restaurantes nuevos de Canadá por enRoute de Air Canada en 2017. Logotipo de Denis Lenarduzzi.", "Der Alder Room, ein intimer Degustationsraum, und Alta, sein legereres Bar- und À-la-carte-Pendant, teilen sich eine Küche und eine reduzierte Materialsprache: dunkle Oberflächen, warmes Holz und präzises Licht, das Essen und Handwerk ins Zentrum stellt. 2017 von Air Canadas enRoute zu Kanadas besten neuen Restaurants gezählt. Logo von Denis Lenarduzzi.", "親密なコース料理のテイスティングルームであるThe Alder Roomと、よりカジュアルなバー兼アラカルトの場であるAltaは、ひとつの厨房と、削ぎ落とされたひとつの素材の言語を共有しています。濃色の面、温かみのある木、そして料理と技を主役に置く精密な照明。2017年、Air CanadaのenRouteによりカナダのベスト・ニュー・レストランのひとつに選出。ロゴデザインはDenis Lenarduzzi。"],
["A menswear environment where retail display and clubroom character share one room.", "Un environnement de mode masculine où présentation commerciale et caractère de club partagent une même salle.", "Un entorno de moda masculina donde la exhibición comercial y el carácter de club comparten una sala.", "Eine Herrenmode-Umgebung, in der Warenpräsentation und Clubraum-Charakter einen Raum teilen.", "物販の什器とクラブルームの性格が、ひとつの部屋に同居するメンズウェアの環境。"],
["Fixture design, millwork, and material direction built around the ritual of menswear: a shop that reads as a room you want to stay in, with the brand carried through every surface.", "Design de mobilier, ébénisterie et direction des matériaux construits autour du rituel de la mode masculine : une boutique qui se lit comme une pièce où l'on veut rester, la marque portée par chaque surface.", "Diseño de mobiliario, carpintería y dirección de materiales construidos en torno al ritual de la moda masculina: una tienda que se lee como una sala donde uno quiere quedarse, con la marca presente en cada superficie.", "Möbeldesign, Einbauten und Materialkonzept rund um das Ritual der Herrenmode: ein Laden, der sich wie ein Raum liest, in dem man bleiben möchte, mit der Marke auf jeder Oberfläche.", "メンズウェアという儀式を軸に組み立てた什器デザイン、造作、マテリアルディレクション。すべての面にブランドが行き渡り、留まっていたくなる部屋として読める店です。"],
["Completed Space", "Espace réalisé", "Espacio terminado", "Fertiggestellter Raum", "竣工した空間"],
["Process / Construction", "Processus / Construction", "Proceso / Construcción", "Prozess / Bau", "プロセス／施工"],
["A 3,000 sq ft modern patio addition for Hell’s Kitchen at Enoch Casino.", "Un agrandissement de terrasse moderne de 3 000 pi² pour Hell's Kitchen au Enoch Casino.", "Una ampliación moderna de patio de 280 m² para Hell's Kitchen en Enoch Casino.", "Ein moderner 3.000 sq ft Terrassenanbau für Hell's Kitchen im Enoch Casino.", "Enoch CasinoのHell’s Kitchenのための、約280㎡のモダンなパティオ増築。"],
["A compact architectural extension of glass, concrete, black metal, and warm soffit material, giving the restaurant a stronger exterior presence, an improved arrival sequence, and a refined indoor-outdoor relationship with the larger casino building.", "Une extension architecturale compacte de verre, béton, métal noir et sous-face chaleureuse, donnant au restaurant une présence extérieure affirmée, une meilleure séquence d'arrivée et une relation intérieur-extérieur raffinée avec le casino.", "Una extensión arquitectónica compacta de vidrio, hormigón, metal negro y sofito cálido, dando al restaurante una presencia exterior más fuerte, una mejor secuencia de llegada y una relación interior-exterior refinada con el edificio del casino.", "Eine kompakte architektonische Erweiterung aus Glas, Beton, schwarzem Metall und warmer Untersicht, die dem Restaurant eine stärkere Außenpräsenz, eine bessere Ankunftssequenz und ein verfeinertes Innen-Außen-Verhältnis zum Casinogebäude gibt.", "ガラス、コンクリート、黒い金属、温かみのある軒天材によるコンパクトな建築的増築。レストランに、より強い外観の存在感と、改善されたアプローチの流れ、そしてカジノ本体との洗練された内外の関係をもたらしています。"],
["A multi-year initiative reimagining ATB Financial’s flagship and neighbourhood branches.", "Une initiative pluriannuelle réinventant les succursales phares et de quartier d'ATB Financial.", "Una iniciativa plurianual que reinventa las sucursales insignia y de barrio de ATB Financial.", "Eine mehrjährige Initiative zur Neugestaltung der Flagship- und Quartiersfilialen von ATB Financial.", "ATB Financialの旗艦店舗と地域店舗を再構想する、複数年にわたる取り組み。"],
["Strategic planning, concept development, and design direction for “Branches of the Future”: banking environments rebuilt around customer experience, with a design system flexible enough to scale across Alberta.", "Planification stratégique, développement conceptuel et direction de design des « Branches of the Future » : des environnements bancaires reconstruits autour de l'expérience client, avec un système de design assez souple pour s'étendre à toute l'Alberta.", "Planificación estratégica, desarrollo conceptual y dirección de diseño de “Branches of the Future”: entornos bancarios reconstruidos en torno a la experiencia del cliente, con un sistema de diseño lo bastante flexible para escalar por toda Alberta.", "Strategische Planung, Konzeptentwicklung und Designleitung für „Branches of the Future“: Bankumgebungen, neu gebaut um das Kundenerlebnis, mit einem Designsystem, das flexibel genug ist, um in ganz Alberta zu skalieren.", "「Branches of the Future」の戦略立案、コンセプト開発、デザインディレクション。顧客体験を軸に組み立て直された銀行の環境と、アルバータ州全域へ展開できる柔軟なデザインシステム。"],
["Architect: Stantec", "Architecte : Stantec", "Arquitecto: Stantec", "Architekt: Stantec", "建築設計：Stantec"],
["Architect: Lemay", "Architecte : Lemay", "Arquitecto: Lemay", "Architekt: Lemay", "建築設計：Lemay"],
["A café and marketplace concept for a downtown Calgary workplace.", "Un concept de café et marché pour un milieu de travail du centre-ville de Calgary.", "Un concepto de café y mercado para un lugar de trabajo en el centro de Calgary.", "Ein Café- und Marktkonzept für einen Arbeitsplatz in der Innenstadt von Calgary.", "カルガリー中心部のワークプレイスのための、カフェとマーケットプレイスの構想。"],
["A full food-and-retail program developed in concept: an oak service bar with marketplace shelving at entry, a café floor opening to the lobby stair, and a dining hall of booths, communal tables, and a servery beyond.", "Un programme complet de restauration et commerce développé en concept : un bar de service en chêne avec étagères de marché à l'entrée, un café ouvrant sur l'escalier du hall et une salle à manger de banquettes, tables communes et comptoir de service.", "Un programa completo de gastronomía y comercio desarrollado en concepto: una barra de servicio de roble con estantería de mercado en la entrada, un piso de café que se abre a la escalera del vestíbulo y un comedor de reservados, mesas comunes y un mostrador de servicio.", "Ein komplettes Gastronomie- und Handelsprogramm im Konzept: eine Eichen-Servicebar mit Marktregalen am Eingang, eine Caféfläche zur Lobbytreppe und ein Speisesaal mit Sitznischen, Gemeinschaftstischen und Ausgabe.", "飲食と物販の全体プログラムをコンセプトとして開発しました。入口にマーケット什器を伴うオーク材のサービスバー、ロビーの階段へ開くカフェのフロア、そしてその奥にブース席と大テーブル、サーヴェリーを備えたダイニングホール。"],
["Concept Renderings", "Rendus conceptuels", "Renders conceptuales", "Konzept-Renderings", "コンセプトレンダリング"],
["Café bar & dining hall", "Bar-café et salle à manger", "Barra de café y comedor", "Cafébar & Speisesaal", "カフェバーとダイニングホール"],
["A private members’ club on the main floor of the Edison in downtown Calgary.", "Un club privé au rez-de-chaussée de l'Edison, au centre-ville de Calgary.", "Un club privado de socios en la planta principal del Edison, en el centro de Calgary.", "Ein privater Mitgliederclub im Erdgeschoss des Edison in der Innenstadt von Calgary.", "カルガリー中心部のEdison1階にある、会員制のプライベートクラブ。"],
["A long bar of blackened steel and stacked concrete block under a walnut-slat ceiling, lounge seating against the Edison’s angled facade, and a pixel-mosaic mural closing the room. The club’s mark is built into the space itself: backlit at the walnut entry and screened across the glazing.", "Un long bar d'acier noirci et de blocs de béton empilés sous un plafond de lattes de noyer, des fauteuils contre la façade inclinée de l'Edison et une murale en mosaïque pixel fermant la salle. La marque du club est intégrée à l'espace : rétroéclairée à l'entrée en noyer et tramée sur le vitrage.", "Una barra larga de acero ennegrecido y bloques de hormigón apilados bajo un techo de listones de nogal, asientos de salón contra la fachada inclinada del Edison y un mural de mosaico pixelado cerrando la sala. La marca del club está integrada en el espacio: retroiluminada en la entrada de nogal y tramada en el acristalamiento.", "Eine lange Bar aus geschwärztem Stahl und gestapeltem Betonstein unter einer Nussbaumlatten-Decke, Loungemöbel an der schrägen Fassade des Edison und ein Pixelmosaik-Wandbild als Raumabschluss. Das Zeichen des Clubs ist in den Raum eingebaut: hinterleuchtet am Nussbaumeingang und als Raster auf der Verglasung.", "クルミ材のルーバー天井の下に、黒染めのスチールと積み上げたコンクリートブロックによる長いバー。Edisonの斜めのファサードに沿うラウンジ席と、部屋を締めくくるピクセルモザイクの壁画。クラブのマークは空間そのものに組み込まれ、クルミ材のエントランスでは背面から照らされ、ガラス面には網点として展開します。"],
["The Club", "Le Club", "El Club", "Der Club", "クラブ"],
["Photography", "Photographie", "Fotografía", "Fotografie", "写真"],
["An optometry clinic and eyewear retail environment.", "Une clinique d'optométrie et un espace de vente de lunetterie.", "Una clínica de optometría y un entorno de venta de gafas.", "Eine Optometrie-Klinik und Brillen-Einzelhandelsumgebung.", "検眼クリニックとアイウェアの物販が一体となった環境。"],
["Clinic and retail resolved as one room: an ash display wall doubling as the exam-room screen, a supergraphic eye chart marking the threshold between the two, and white casework with framed mirror ledges carrying the frame collection down the length of the space.", "Clinique et commerce résolus en une seule salle : un mur d'exposition en frêne servant d'écran aux salles d'examen, une charte visuelle supergraphique marquant le seuil et des rangements blancs aux tablettes-miroirs portant la collection de montures sur toute la longueur.", "Clínica y comercio resueltos como una sola sala: una pared expositora de fresno que sirve de pantalla a las salas de examen, una carta optométrica supergráfica marcando el umbral y mobiliario blanco con repisas de espejo llevando la colección de monturas a lo largo del espacio.", "Klinik und Handel als ein Raum gelöst: eine Eschenholz-Präsentationswand als Sichtschutz der Untersuchungsräume, eine übergroße Sehtafel als Schwelle dazwischen und weiße Einbauten mit gerahmten Spiegelborden, die die Fassungskollektion durch den Raum tragen.", "クリニックと物販をひと部屋として解きました。トネリコの展示壁が検査室のスクリーンを兼ね、大きく引き伸ばした視力表がふたつの領域の境目を示し、白い造作の額縁状のミラー棚がフレームのコレクションを空間の奥まで導きます。"],
["Clinic & Dispensary", "Clinique et lunetterie", "Clínica y óptica", "Klinik & Optik", "クリニックと販売スペース"],
["A commercial repositioning concept for the former RBC building on Jasper Avenue.", "Un concept de repositionnement commercial pour l'ancien édifice RBC sur Jasper Avenue.", "Un concepto de reposicionamiento comercial para el antiguo edificio RBC en Jasper Avenue.", "Ein Konzept zur gewerblichen Neupositionierung des ehemaligen RBC-Gebäudes an der Jasper Avenue.", "Jasper Avenueの旧RBCビルの、商業的リポジショニングの構想。"],
["For Melcor, the study renews the tower’s lower levels: new architectural interventions, exterior plaza work, lighting, landscape, and interior public space shift the building from a closed corporate address into an open, active urban destination. With DIALOG.", "Pour Melcor, l'étude renouvelle les niveaux inférieurs de la tour : interventions architecturales, travail des places extérieures, éclairage, paysage et espaces publics intérieurs font passer l'édifice d'une adresse corporative fermée à une destination urbaine ouverte et active. Avec DIALOG.", "Para Melcor, el estudio renueva los niveles inferiores de la torre: nuevas intervenciones arquitectónicas, trabajo de plazas exteriores, iluminación, paisaje y espacio público interior convierten el edificio de una dirección corporativa cerrada en un destino urbano abierto y activo. Con DIALOG.", "Für Melcor erneuert die Studie die unteren Ebenen des Turms: neue architektonische Eingriffe, Außenplätze, Beleuchtung, Landschaft und innere öffentliche Räume verwandeln das Gebäude von einer geschlossenen Firmenadresse in ein offenes, aktives urbanes Ziel. Mit DIALOG.", "Melcorのためのこのスタディは、タワーの下層階を刷新します。新たな建築的介入、外部広場の整備、照明、ランドスケープ、内部の公共空間によって、閉じた企業の住所から、開かれた活気ある都市の目的地へと建物を変えていきます。DIALOGとの協働。"],
["A concept for elders housing with Enoch Cree Nation.", "Un concept de logement pour aînés avec la Nation crie d'Enoch.", "Un concepto de vivienda para mayores con la Nación Cree de Enoch.", "Ein Wohnkonzept für Älteste mit der Enoch Cree Nation.", "Enoch Cree Nationとともに進める、高齢者住宅の構想。"],
["A housing concept shaped around community, culture, and care: shared gathering space at the heart, dwellings arranged for connection, dignity, and everyday visits.", "Un concept de logement façonné autour de la communauté, de la culture et du soin : un espace de rassemblement au cœur, des logements disposés pour la connexion, la dignité et les visites quotidiennes.", "Un concepto de vivienda formado en torno a la comunidad, la cultura y el cuidado: espacio de reunión compartido en el centro, viviendas dispuestas para la conexión, la dignidad y las visitas cotidianas.", "Ein Wohnkonzept um Gemeinschaft, Kultur und Fürsorge: gemeinsamer Versammlungsraum im Herzen, Wohnungen angeordnet für Verbindung, Würde und alltägliche Besuche.", "コミュニティ、文化、ケアを軸にかたちづくられた住まいの構想。中心に共有の集いの場を置き、つながりと尊厳、そして日々の訪れのために住戸を配置しています。"],
["Clear planning, efficient SIP panelized construction, warm materials, natural light, and protected outdoor connections create an environment focused on privacy, safety, dignity, and recovery. With MES Architecture.", "Une planification claire, une construction efficace en panneaux SIP, des matériaux chauds, la lumière naturelle et des liens extérieurs protégés créent un environnement axé sur l'intimité, la sécurité, la dignité et le rétablissement. Avec MES Architecture.", "Planificación clara, construcción eficiente con paneles SIP, materiales cálidos, luz natural y conexiones exteriores protegidas crean un entorno centrado en la privacidad, la seguridad, la dignidad y la recuperación. Con MES Architecture.", "Klare Planung, effiziente SIP-Elementbauweise, warme Materialien, natürliches Licht und geschützte Außenverbindungen schaffen ein Umfeld für Privatsphäre, Sicherheit, Würde und Genesung. Mit MES Architecture.", "明快な計画、効率的なSIPパネル工法、温かみのある素材、自然光、そして守られた屋外とのつながりが、プライバシー、安全、尊厳、回復に焦点を当てた環境をつくります。MES Architectureとの協働。"]
];
var DICT={fr:{},es:{},de:{},ja:{}};
T.forEach(function(r){DICT.fr[r[0]]=r[1];DICT.es[r[0]]=r[2];DICT.de[r[0]]=r[3];DICT.ja[r[0]]=r[4];});
var LK='sudu-lang', ATTRS=['alt','placeholder','title','aria-label','data-info'];
var cur='en', walking=false;
function xl(s,lang){if(lang==='en')return s;var d=DICT[lang];return d&&d[s]||null;}
var REV=null;
function buildRev(){REV={};Object.keys(DICT).forEach(function(l){var d=DICT[l];Object.keys(d).forEach(function(k){var v=d[k];if(v&&REV[v]===undefined)REV[v]=k;});});}
function toEn(k){if(!REV)buildRev();return REV[k]!==undefined?REV[k]:k;}
function skip(el){return !!(el&&el.closest&&el.closest('#langSwitch,#dmSwatches,script,style'));}
function walk(){
  walking=true;
  var tw=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null);
  var n;
  while(n=tw.nextNode()){
    var p=n.parentNode;
    if(!p)continue;
    var pn=p.nodeName;
    if(pn==='SCRIPT'||pn==='STYLE'||pn==='NOSCRIPT')continue;
    if(skip(p))continue;
    var raw=n.textContent, key=raw.replace(/\s+/g,' ').trim();
    if(!key)continue;
    var en=toEn(key);
    var target=cur==='en'?en:(xl(en,cur)||en);
    if(target!==key)n.textContent=raw.replace(raw.trim(),target);
  }
  document.querySelectorAll('['+ATTRS.join('],[')+']').forEach(function(el){
    if(skip(el))return;
    ATTRS.forEach(function(a){
      var v=el.getAttribute(a);
      if(!v)return;
      var key=v.replace(/\s+/g,' ').trim();
      if(!key)return;
      var en=toEn(key);
      var target=cur==='en'?en:(xl(en,cur)||en);
      if(target!==key)el.setAttribute(a,target);
    });
  });
  document.documentElement.setAttribute('lang',cur);
  walking=false;
}
function setLang(l){
  cur=l;
  if(l==='ja')ensureJaFont();
  try{localStorage.setItem(LK,l);}catch(e){}
  walk();
  buildSwitcher();
  // storage in this webview can lag a tick; re-assert so a reload restores the right language
  try{if(localStorage.getItem(LK)!==l)localStorage.setItem(LK,l);}catch(e){}
}
/* Urbanist carries no CJK glyphs, so Japanese would otherwise fall back to
   whatever each device happens to supply. Noto Sans JP is fetched only when
   Japanese is actually selected, and sits *after* Urbanist in the stack so
   Latin runs (SuDu Studio, DIALOG, project names) still set in Urbanist and
   only the CJK glyphs fall through to it.
   The family has to be forced with !important because the pages carry
   font-family in inline style attributes, which a plain rule cannot outrank.
   Letter-spacing is reset for the same reason: the display type tracks as
   tight as -0.12em, which collides CJK glyphs outright. Japanese sets solid
   by convention, so normal is both the correct and the safe value. The
   language switcher itself stays Latin, so it keeps its tracking. */
var jaFont=false;
function ensureJaFont(){
  if(jaFont)return;jaFont=true;
  var l=document.createElement('link');
  l.rel='stylesheet';
  l.href='https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap';
  document.head.appendChild(l);
  var st=document.createElement('style');
  st.textContent='html[lang="ja"] *{font-family:\'Urbanist\',\'Noto Sans JP\',sans-serif !important;letter-spacing:normal !important;}'+
    'html[lang="ja"] #langSwitch,html[lang="ja"] #langSwitch *{letter-spacing:0.08em !important;}';
  document.head.appendChild(st);
}
function buildSwitcher(){
  var wrap=document.getElementById('langSwitch');
  if(!wrap){
    if(!document.body)return;
    wrap=document.createElement('div');
    wrap.id='langSwitch';
    /* Position, ground and blur come from the chrome bar (js/chrome-bar.js),
       which is where all three pills live. The fallback keeps the switcher
       reachable in the corner if the bar script ever fails to load. */
    if(window.suduBar)window.suduBar().appendChild(wrap);
    else{wrap.style.cssText='position:fixed;left:clamp(20px,4.5vw,64px);bottom:16px;z-index:9999;display:flex;gap:11px;align-items:center;padding:6px 12px;background:transparent;border:0.5px solid currentColor;border-radius:22px;';document.documentElement.appendChild(wrap);}
  }
  if(wrap.getAttribute('data-cur')===cur)return;
  wrap.setAttribute('data-cur',cur);
  wrap.innerHTML='';
  ['en','fr','es','de','ja'].forEach(function(l){
    if(l===cur)return;
    var b=document.createElement('button');
    b.type='button';b.textContent=l.toUpperCase();b.setAttribute('data-lang-btn',l);
    b.style.cssText='background:none;border:0;padding:0;cursor:none;color:inherit;font:inherit;font-size:10.5px;font-weight:500;letter-spacing:0.08em;height:13px;line-height:13px;opacity:0.75;';

    wrap.appendChild(b);
  });
}
document.addEventListener('click',function(e){
  var t=e.target&&e.target.closest&&e.target.closest('[data-lang-btn]');
  if(!t)return;
  e.preventDefault();
  setLang(t.getAttribute('data-lang-btn'));
});
window.__i18n={get cur(){return cur;},setLang:setLang,langs:Object.keys(DICT),probe:function(s){return {en:toEn(s),de:xl(toEn(s),'de'),es:xl(toEn(s),'es'),fr:xl(toEn(s),'fr'),ja:xl(toEn(s),'ja')};}};
var deb;
new MutationObserver(function(){
  if(walking)return;
  clearTimeout(deb);
  deb=setTimeout(function(){buildSwitcher();walk();},120);
}).observe(document.documentElement,{childList:true,subtree:true});
var INIT=false;
function init(){
  if(INIT)return;INIT=true;
  buildSwitcher();
  var saved='en';
  try{saved=localStorage.getItem(LK)||'en';}catch(e){}
  setLang(saved);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
[600,1800,3500].forEach(function(t){setTimeout(function(){buildSwitcher();if(cur!=='en')walk();},t);});
})();

})();
}
